### ISSUE TITLE
Some issues in README

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-robotlog2db#18]
See attached pdf ...
[RobotLog2DB.pdf](https://github.com/test-fullautomation/robotframework-robotlog2db/files/10020274/RobotLog2DB.pdf)

**Comment by test-fullautomation** [comment]
Hi Ngoan,
so, I can close this issue?
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
> Hi Ngoan, so, I can close this issue? Thank you, Thomas

Hi Thomas,

Yes, this issue can be closed.
README file has been updated according to suggestions from Holger in the PR #19 as below:
https://github.com/test-fullautomation/robotframework-robotlog2db/commit/0a2b99fad47f03679329441afce93cfecd577393#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168f

Thank you,
Ngoan
