### ISSUE TITLE
Link to licence in README twice

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-robotlog2db#20]
The README.rst contains:

RobotLog2DB
===========

|License: Apache v2|

Table of Contents
-----------------

Are you sure that this "|License: Apache v2|" is required at the top of the file? The full licence text is already present at the bottom of the file.

**Comment by ngoan1608** [comment]
Hi Holger,

Thank you for your finding, the duplicated link is my mistake. 
I have fixed in the PR #21 .

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
merged with #21
