### ISSUE TITLE
Some findings in documentation

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-robotlog2db#24]
[RobotLog2DB_2.pdf](https://github.com/test-fullautomation/robotframework-robotlog2db/files/10557418/RobotLog2DB_2.pdf)

**Comment by test-fullautomation** [comment]
Hi Ngoan,
pleas look into this.
Thank you,
 Thomas

**Comment by HolQue** [comment]
Is there a certain reason for the plural:

`--versions VERSIONS`

I would expect

`--version VERSION`

because you only provide a single version.

**Comment by test-fullautomation** [comment]
solved with #44
