### ISSUE TITLE
Append mode together with mapping table may have an issue

### ISSUE THREAD

**Issue by HolQue** [test-fullautomation/robotframework-robotlog2db#31]
RobotLog2DB has same issue than PyTestLog2db.

See:

https://github.com/test-fullautomation/python-pytestlog2db/issues/12

Every "append" adds another entry of the same component name in the component selection box of the dashoard. But the number of tests are not increased. This means: The values are not accumulated under one common entry in the component selection box of the dashoard, but still separated and selectable by individual entries in the component selection box.

This happens only in case of a mapping table is involved.

Currently visible in test database under:

`QT-007 / apptest-007 / RobotFrameworkExtensions`

**Comment by HolQue** [comment]
Values displayed properly now.

(retest with latest available feature branches / 28.02.2023)

**Comment by ngoan1608** [comment]
Hi Thomas,

This ticket can be closed as https://github.com/test-fullautomation/python-pytestlog2db/issues/12 because the **testdb** has been updated properly.

Thank you,
Ngoan
