### ISSUE TITLE
Installation is not running. Needed Module is missing

### ISSUE THREAD

**Issue by gdroes** [test-fullautomation/robotframework-robotlog2db#49]
As you have removed the Module "PythonExtensionsCollection" 4 month ago the installation is crashing by using this module.

  File "C:\robotframework-robotlog2db\config\CRepositoryConfig.py", line 40, in <module>
    from PythonExtensionsCollection.String.CString import CString
ModuleNotFoundError: No module named 'PythonExtensionsCollection'

**Comment by ngoan1608** [comment]
Hi @gdroes ,

Thank you for your finding!

**RobotLog2DB** is now available on PyPI so that install this package directly as below command:
```
pip install robotframework-robotlog2db
```

`README` file is not up-to-date due to package's changes. I am updating it accordingly.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @gdroes,

issue should be fixed with already merged #48 and #50 .
PyPi package is updated accordingly.
https://pypi.org/project/robotframework-robotlog2db/

Please check and confim.

Thank you,
 Thomas

**Comment by gdroes** [comment]
Thanks, the installation is working now.

**Comment by test-fullautomation** [comment]
very good!
