### ISSUE TITLE
unable to process RF schemaversion >=3

### ISSUE THREAD

**Issue by gdroes** [test-fullautomation/robotframework-robotlog2db#51]
The latest Robotframework Version 6.1 is creating a schemaversion="4". But robotlog2db can only work up to 3.

Reason: Element 'robot', attribute 'schemaversion': [facet 'maxInclusive'] The value '4' is greater than the maximum value allowed ('3')., line 2

**Comment by test-fullautomation** [comment]
Hi @gdroes,

Thank you for your finding!
As RobotFramework 6.1 was release few days ago we did not yet adapt to it.
Is this urgent for you? Other wise we would adapt in few weeks.

Thank you,
 Thomas

**Comment by gdroes** [comment]
Hi @test-fullautomation,
you can take your time. Maybe we see other changes from Robotframework 6.1 also.
Best regards
Gerhard

**Comment by test-fullautomation** [comment]
Hi Gerhard,
O.K. very good! Please inform us in case of other issues.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi  @gdroes,
new pip version 1.3.9 should fix this issue.
Thank you,
 Thomas
