### ISSUE TITLE
unable to extract suite.starttime from output.xml with multilevel suite results

### ISSUE THREAD

**Issue by gdroes** [test-fullautomation/robotframework-robotlog2db#53]
robotlog2db fail by processing output.xml with nested suite results.

Error:
Could not create new execution result in database. Reason: expected string or bytes-like object, got 'NoneType'
[output.zip](https://github.com/test-fullautomation/robotframework-robotlog2db/files/11813826/output.zip)

**Comment by ngoan1608** [comment]
Hi @gdroes ,

Thank you for your finding!

It seems that the given result *.xml file is merged result of multiple *.xml files with `rebot`.
The generated `starttime` and `endtime` of root suite are both set to `N/A` and tool this not cover this scenario.

I am updating tool accordingly and create PR soon.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi @gdroes ,
bug should be fixed with version 1.3.8 available now in pypi: https://pypi.org/project/robotframework-robotlog2db/
Please give short feedback.
Best regards,
 Thomas

**Comment by gdroes** [comment]
Hi @test-fullautomation, the test file seems running fine. But while running tests with similar output files we still see an issue.

Error:
Could not create new execution result in database. Reason: '<' not supported between instances of 'NoneType' and 'str'
[output05.zip](https://github.com/test-fullautomation/robotframework-robotlog2db/files/11829262/output05.zip)

Best regards,
Gerhard

**Comment by test-fullautomation** [comment]
Hi @gdroes ,
unfortunately I was ill and could not process the bugfix provied by @ngoan1608 .
I'll do this in the next days.
Thank you,
 Thomas

**Comment by test-fullautomation** [comment]
Hi  @gdroes,
new pip version 1.3.9 should fix this issue.
Thank you,
 Thomas
